### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by anteriovieira** [egoist/vue-no-ssr#2]
@egoist 

Instead of using

```js
process.env.NODE_ENV === 'development'
```
Can we change to the code below?

~~process.browser~~ !process.browser

**Comment by egoist** [comment]
Why?

**Comment by anteriovieira** [comment]
I have no use case for this. It made more sense to me using a `process.browser` and I thought could remove the dependency on the environment variable.

My thinking is wrong?

**Comment by egoist** [comment]
I'm using this because I want it to throw error in development only.

**Comment by anteriovieira** [comment]
Sorry, what I was saying was `!process.browser ` or `process.server`. It would be any server-side ambieten and not just developement

**Comment by anteriovieira** [comment]
cc @egoist 

Example:

```js
export default {
  name: 'no-ssr',
  props: ['placeholder'],
  data() {
    return {
      canRender: false
    }
  },
  mounted() {
    this.canRender = true
  },
  render(h) {
    if (this.canRender) {
      if (
        process.env.NODE_ENV === 'development' &&
        this.$slots.default.length > 1
      ) {
        throw new Error('[vue-no-ssr] You cannot use multiple child components')
      }
      return this.$slots.default[0]
    }
    return h(
      'div',
      {
        class: ['no-ssr-placeholder']
      },
      this.placeholder
    )
  }
}
```
