### ISSUE TITLE
Placeholder generates invalid HTML markup

### ISSUE THREAD

**Issue by saawsan** [egoist/vue-no-ssr#8]
Because the markup of the vue-no-ssr placeholder is a `div`, it can generate invalid HTML markup if it is nested inside an inline element (or a block element that only accepts inline element).

**This code is valid:** 
```
<div><no-ssr>Lorem</no-ssr></div>
<div><div class="no-ssr-placeholder"></div></div>
```

**This code is invalid:** 

```
<p><no-ssr>Lorem</no-ssr></div>
<p><div class="no-ssr-placeholder"></div></p>
```
And Nuxt will output the following error:

`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Suggested solution**
Insert the No-SRR placeholder with a `<span>` instead of a `<div>`.

**Comment by egoist** [comment]
I added a `placeholderTag` (or `placeholder-tag`) prop for this https://github.com/egoist/vue-no-ssr#placeholder
